from types import SimpleNamespace

import fitz
import pytest

import app.ingestion.vision as vision_mod
from app.core.errors import ExtractionError
from app.ingestion.detector import get_extractor
from app.ingestion.models import ElementType
from app.ingestion.pdf import extract_pdf


def _make_pdf(pages: list[str]) -> bytes:
    doc = fitz.open()
    for text in pages:
        page = doc.new_page()
        page.insert_text((72, 72), text)
    data = doc.tobytes()
    doc.close()
    return data


def _make_pdf_with_image() -> bytes:
    doc = fitz.open()
    page = doc.new_page()
    pix = fitz.Pixmap(fitz.csRGB, fitz.IRect(0, 0, 64, 64))
    pix.clear_with(200)  # light-gray 64x64 image, generated by mupdf itself
    page.insert_image(fitz.Rect(50, 50, 200, 200), pixmap=pix)
    data = doc.tobytes()
    doc.close()
    return data


def test_extract_pdf_text_and_pages() -> None:
    result = extract_pdf("sample.pdf", _make_pdf(["Hello from page one", "Second page content"]))
    assert result.format == "pdf"
    assert result.num_units == 2
    paras = [e for e in result.elements if e.element_type == ElementType.PARAGRAPH]
    assert len(paras) == 2
    assert paras[0].location.page == 1
    assert "Hello from page one" in paras[0].text
    assert len(result.file_hash) == 64


def test_extract_pdf_blank_raises() -> None:
    doc = fitz.open()
    doc.new_page()  # blank: no text, no images
    data = doc.tobytes()
    doc.close()
    with pytest.raises(ExtractionError):
        extract_pdf("blank.pdf", data)


def test_extract_pdf_scanned_page_via_vision(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(vision_mod, "describe_image", lambda blob, mime: "scanned invoice text")
    monkeypatch.setattr(
        vision_mod,
        "get_settings",
        lambda: SimpleNamespace(vision_min_image_kb=0, vision_max_images=10),
    )
    result = extract_pdf("scan.pdf", _make_pdf_with_image())
    image_els = [e for e in result.elements if e.element_type == ElementType.IMAGE]
    assert any("scanned invoice text" in e.text for e in image_els)
    assert image_els[0].location.page == 1


def test_pdf_extractor_is_registered() -> None:
    assert get_extractor("pdf") is extract_pdf
